# Generated by Django 5.0.1 on 2024-02-15 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('nationality', models.CharField(blank=True, max_length=30)),
                ('marital_status', models.BooleanField(default=False)),
                ('spouse', models.CharField(blank=True, max_length=100)),
                ('parents', models.CharField(blank=True, max_length=100)),
                ('siblings', models.CharField(blank=True, max_length=200)),
                ('upcoming_movie', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('picture_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('rating', models.CharField(blank=True, max_length=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, help_text='In dollars', max_length=20, null=True)),
                ('collections', models.CharField(blank=True, help_text='In dollars', max_length=20, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='rohapp.actors')),
            ],
        ),
    ]
