# Generated by Django 5.0.1 on 2024-02-22 06:14

from django.db import migrations,models

def add_data(apps, schema_editor):

    Actors = apps.get_model('rohapp', 'Actors')
    Movies = apps.get_model('rohapp','Movies')

    actors = {
        'name': "NTR",
        'birthdate': "1983-05-20",
        'nationality': "Indian",
        'marital_status':True,
        'spouse' : "Pranathi Nandamuri",
        'parents' : "Hari Krishna and Shalini Bhaskar Rao",
        'siblings' : "Nandamuri Kalyan Ram ",
        'upcoming_movie' : "Devara",
        'description' : "Great Actor",
        'picture_url' : "https://images.app.goo.gl/YqDgNm2JAxYeHtfw9"

    }
    a1 = Actors.objects.create(**actors)

    movie_1 = {
        'title' : "Devara",
        'genre' : "Action Thriller",
        'rating' :"",
        'release_date' : "2024-07-01",
        'budget' : "$70 million",
        'collections': "",
        'actor': a1

    }
    Movies.objects.create(**movie_1)

    movie_2 = {
        'title' : "RRR",
        'genre' : "Action Thriller",
        'rating' :"3.7/5",
        'release_date' : "2022-03-30",
        'budget' : "$350 million",
        'collections': "$700 million",
        'actor': a1

    }
    Movies.objects.create(**movie_2)
    
class Migration(migrations.Migration):

    dependencies = [
        ('rohapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
